name: Dagdan Stock Monitor

on:
  workflow_dispatch:

jobs:
  check-stock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run checker
        run: python main.py

      - name: Wait 15 minutes
        run: sleep 900

      - name: Trigger next run
        run: |
          curl -X POST https://api.github.com/repos/ftalpaca/dagdan-stock-monitor/actions/workflows/$(basename $GITHUB_WORKFLOW)/dispatches \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"ref":"main"}'
